import { Agency, Analytics } from './types';

export const mockAgencies: Agency[] = [
  {
    id: '1',
    name: 'Digital Growth Labs',
    logo: '🔵',
    services: ['SEO', 'PPC', 'Content'],
    rating: 4.9,
    reviewCount: 127,
    location: 'San Francisco, CA',
    state: 'CA',
    url: 'https://digitalgrowth.com',
    description: 'Award-winning digital marketing agency specializing in growth strategies.',
    badge: 'Top Rated'
  },
  {
    id: '2',
    name: 'Blue Wave Marketing',
    logo: '🌊',
    services: ['Social Media', 'Email', 'Content'],
    rating: 4.7,
    reviewCount: 89,
    location: 'New York, NY',
    state: 'NY',
    url: 'https://bluewavemarketing.com',
    description: 'Experts in social media strategy and community building.',
  },
  {
    id: '3',
    name: 'Peak Performance Co',
    logo: '⛰️',
    services: ['PPC', 'SEO', 'Analytics'],
    rating: 4.8,
    reviewCount: 156,
    location: 'Chicago, IL',
    state: 'IL',
    url: 'https://peakperformance.com',
    description: 'Data-driven agency focused on measurable results and ROI.',
    badge: 'Most Reviewed'
  },
  {
    id: '4',
    name: 'Sunrise Marketing Partners',
    logo: '🌅',
    services: ['Web Design', 'SEO', 'Content'],
    rating: 4.6,
    reviewCount: 72,
    location: 'Austin, TX',
    state: 'TX',
    url: 'https://sunrisemarketing.com',
    description: 'Creative agency blending design and digital marketing.',
  },
  {
    id: '5',
    name: 'Urban Digital Studios',
    logo: '🏙️',
    services: ['Social Media', 'Web Design', 'PPC'],
    rating: 4.8,
    reviewCount: 98,
    location: 'Los Angeles, CA',
    state: 'CA',
    url: 'https://urbandigital.com',
    description: 'Cutting-edge agency specializing in urban brand development.',
    badge: 'Trending'
  },
  {
    id: '6',
    name: 'Velocity Growth Hacker',
    logo: '⚡',
    services: ['SEO', 'Analytics', 'Email'],
    rating: 4.9,
    reviewCount: 134,
    location: 'Seattle, WA',
    state: 'WA',
    url: 'https://velocitygrowth.com',
    description: 'Growth-focused agency with proven scaling strategies.',
    badge: 'Top Rated'
  },
  {
    id: '7',
    name: 'Nexus Brand Agency',
    logo: '🔗',
    services: ['PPC', 'Social Media', 'Email', 'Content'],
    rating: 4.5,
    reviewCount: 64,
    location: 'Boston, MA',
    state: 'MA',
    url: 'https://nexusbrand.com',
    description: 'Integrated marketing solutions for B2B companies.',
  },
  {
    id: '8',
    name: 'Catalyst Marketing',
    logo: '⚗️',
    services: ['SEO', 'Content', 'Web Design'],
    rating: 4.7,
    reviewCount: 81,
    location: 'Denver, CO',
    state: 'CO',
    url: 'https://catalystmkt.com',
    description: 'Agency focused on transforming brands through strategic marketing.',
  },
  {
    id: '9',
    name: 'Harmony Digital Group',
    logo: '🎵',
    services: ['Social Media', 'Content', 'Analytics'],
    rating: 4.6,
    reviewCount: 76,
    location: 'Miami, FL',
    state: 'FL',
    url: 'https://harmonydigital.com',
    description: 'Specialized in influencer marketing and brand partnerships.',
  },
  {
    id: '10',
    name: 'Quantum Leap Marketing',
    logo: '🚀',
    services: ['PPC', 'SEO', 'Analytics', 'Email'],
    rating: 4.8,
    reviewCount: 142,
    location: 'San Diego, CA',
    state: 'CA',
    url: 'https://quantumleap.com',
    description: 'Innovative agency pushing boundaries in digital marketing.',
  },
  {
    id: '11',
    name: 'Prism Media Solutions',
    logo: '🎨',
    services: ['Web Design', 'Social Media', 'Content'],
    rating: 4.4,
    reviewCount: 58,
    location: 'Portland, OR',
    state: 'OR',
    url: 'https://prismmedia.com',
    description: 'Creative agency with focus on visual storytelling.',
  },
  {
    id: '12',
    name: 'Elite Growth Partners',
    logo: '⭐',
    services: ['PPC', 'Analytics', 'Web Design', 'Email'],
    rating: 4.9,
    reviewCount: 168,
    location: 'Atlanta, GA',
    state: 'GA',
    url: 'https://elitegrowth.com',
    description: 'Premium agency for enterprise-level marketing solutions.',
    badge: 'Top Rated'
  },
];

export const mockAnalytics: Analytics = {
  totalAgencies: 1250,
  avgRating: 4.7,
  locationsCount: 48,
  serviceBreakdown: {
    'SEO': 450,
    'PPC': 380,
    'Social Media': 420,
    'Content': 380,
    'Email': 290,
    'Web Design': 320,
    'Analytics': 210,
  },
};

export const US_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
  'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
  'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
  'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
];

export const SERVICES = ['SEO', 'PPC', 'Social Media', 'Content', 'Email', 'Web Design', 'Analytics'] as const;

export const SERVICE_COLORS: Record<string, string> = {
  'SEO': 'bg-green-100 text-green-700 border-green-200',
  'PPC': 'bg-orange-100 text-orange-700 border-orange-200',
  'Social Media': 'bg-pink-100 text-pink-700 border-pink-200',
  'Content': 'bg-blue-100 text-blue-700 border-blue-200',
  'Email': 'bg-purple-100 text-purple-700 border-purple-200',
  'Web Design': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Analytics': 'bg-slate-100 text-slate-700 border-slate-200',
};
